msrv = "1.85.0"
avoid-breaking-exported-api = true
cognitive-complexity-threshold = 25
too-many-arguments-threshold = 7
too-many-lines-threshold = 100
allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-dbg-in-tests = true
